In [117]:
# i need a file to take a large string and get one specific piece.
# I just want the J2000 RA/Dec, in the format "RA[0] RA[1] RA[2] & Dec[0] Dec[1] Dec[2]"

strinput = """Pluto
Type: dwarf planet
Magnitude: 14.48
Absolute Magnitude: -1.00
Mean Opposition Magnitude: 15.12
RA/Dec (J2000.0): 20h24m20.11s/-23°43'18.4"
RA/Dec (on date): 20h25m55.74s/-23°38'05.7"
HA/Dec: 0h00m27.49s/-23°38'05.7" 
Az./Alt.: +180°07'50.5"/+36°36'06.1" 
Gal. long./lat.: +19°59'04.2"/-30°18'50.5"
Supergal. long./lat.: +235°52'48.4"/+44°56'06.5"
Ecl. long./lat. (J2000.0): +302°43'57.6"/-4°17'21.8"
Ecl. long./lat. (on date): +303°06'32.4"/-4°17'38.5"
Ecliptic obliquity (on date): +23°26'08.9"
Mean Sidereal Time: 20h26m22.7s
Apparent Sidereal Time: 20h26m23.2s
Rise: 15h59m
Transit: 21h00m
Set: 2h05m
Parallactic Angle: +0°07'25.7"
IAU Constellation: Cap
Hourly motion: +0°00'01" towards 262.6°
Hourly motion: dα=-0°00'01" dδ=-0°00'00"
Elongation: 113°08'43.9"
Elong. in Ecl.Long.: E113°13'20"
Phase angle: +1°28'50.5"
Distance from Sun: 35.611 AU (5327.396 M km)
Distance: 35.203 AU (5266.288 M km)
Light time: 4h52m46.4s 
Sidereal period: 90797.00 days (248.589 a)
Apparent diameter: +0°00'00.09"
Diameter: 2376.6 km
Sidereal day: 153h17m36.1s
Mean solar day: 153h16m57.2s
Equatorial rotation velocity: 13.529 m/s
Position Angle of axis: +13°26'51"
Center point: Le=+139°54'16" φe: +59°21'47"
Subsolar point: Ls=+142°29'58" φs: +60°03'20"
Albedo: 0.55
Discovered: 23 January 1930 (C.W. Tombaugh)
Solar Az./Alt.: +280°50'33"/-25°43'14"
Lunar Az./Alt.: +31°36'60"/-25°35'53"
"""

In [118]:
strinput_lines = strinput.splitlines()[5]
print(strinput_lines)
radec2000 = strinput_lines.split(":")[1].strip().replace('Â', '').replace('h', 'h ').replace('m', 'm ').replace('s', 's').replace('°', '° ').replace("'", "' ").replace('/', '&')
print(radec2000)

RA/Dec (J2000.0): 20h24m20.11s/-23°43'18.4"
20h 24m 20.11s&-23° 43' 18.4"

In [119]:
import pandas as pd

In [ ]:
first = '2026-09-28'
second = '2026-09-29'
observations = pd.DataFrame({'Object': [
    'Vega', 'Deneb', 'Sadr', 'Epsilon Cygni', 'Altair', 'Saturn', 'Enif', 'Schedar', 'Fomalhaut',
    'Alpheratz', 'Mirach', 'Mirfak', 'Polaris', 'Kochab', 'Tarazed'

], 'Date': [first, first, first, first, first, first, first, first, first,
    second, second, second, second, second, second]
    , 'Time': [2155, 2201, 2203, 2206, 2207, 2209, 2215, 2223, 2255,
        2222, 2235, 2226, 2230, 2233, 2240]
    , 'General Direction': ['NaN', 'NaN', 'NaN', 'NaN', 'W', 'SE', 'SE', 'NE', 'SE',
        'SE', 'SE', 'NE', 'N',  'NW', 'SW']
})

observations

           Object        Date  Time General Direction
0            Vega  2024-09-28  2155               NaN
1           Deneb  2024-09-28  2201               NaN
2            Sadr  2024-09-28  2203               NaN
3   Epsilon Cygni  2024-09-28  2206               NaN
4          Altair  2024-09-28  2207                 W
5          Saturn  2024-09-28  2209                SE
6            Enif  2024-09-28  2215                SE
7         Schedar  2024-09-28  2223                NE
8       Fomalhaut  2024-09-28  2255                SE
9       Alpheratz  2024-09-29  2222                SE
10         Mirach  2024-09-29  2235                SE
11         Mirfak  2024-09-29  2226                NE
12        Polaris  2024-09-29  2230                 N
13         Kochab  2024-09-29  2233                NW
14        Tarazed  2024-09-29  2240                SW

In [138]:
# Create a new column 'Date/Time' by combining 'Date' and 'Time'

observations['Date/Time'] = pd.to_datetime(observations['Date'] + ' ' + observations['Time'].astype(str), format='%Y-%m-%d %H%M', errors='coerce')

In [142]:
observations.drop(columns=['Date', 'Time'], inplace=True)

In [143]:
observations

           Object General Direction           Date/Time
0            Vega               NaN 2024-09-28 21:55:00
1           Deneb               NaN 2024-09-28 22:01:00
2            Sadr               NaN 2024-09-28 22:03:00
3   Epsilon Cygni               NaN 2024-09-28 22:06:00
4          Altair                 W 2024-09-28 22:07:00
5          Saturn                SE 2024-09-28 22:09:00
6            Enif                SE 2024-09-28 22:15:00
7         Schedar                NE 2024-09-28 22:23:00
8       Fomalhaut                SE 2024-09-28 22:55:00
9       Alpheratz                SE 2024-09-29 22:22:00
10         Mirach                SE 2024-09-29 22:35:00
11         Mirfak                NE 2024-09-29 22:26:00
12        Polaris                 N 2024-09-29 22:30:00
13         Kochab                NW 2024-09-29 22:33:00
14        Tarazed                SW 2024-09-29 22:40:00

In [144]:
observations.to_latex(index=False, escape=False)

'\\begin{tabular}{lll}\n\\toprule\nObject & General Direction & Date/Time \\\\\n\\midrule\nVega & NaN & 2024-09-28 21:55:00 \\\\\nDeneb & NaN & 2024-09-28 22:01:00 \\\\\nSadr & NaN & 2024-09-28 22:03:00 \\\\\nEpsilon Cygni & NaN & 2024-09-28 22:06:00 \\\\\nAltair & W & 2024-09-28 22:07:00 \\\\\nSaturn & SE & 2024-09-28 22:09:00 \\\\\nEnif & SE & 2024-09-28 22:15:00 \\\\\nSchedar & NE & 2024-09-28 22:23:00 \\\\\nFomalhaut & SE & 2024-09-28 22:55:00 \\\\\nAlpheratz & SE & 2024-09-29 22:22:00 \\\\\nMirach & SE & 2024-09-29 22:35:00 \\\\\nMirfak & NE & 2024-09-29 22:26:00 \\\\\nPolaris & N & 2024-09-29 22:30:00 \\\\\nKochab & NW & 2024-09-29 22:33:00 \\\\\nTarazed & SW & 2024-09-29 22:40:00 \\\\\n\\bottomrule\n\\end{tabular}\n'

In [130]:
observations

           Object       Date                Time General Direction
0            Vega 2024-09-28 1900-01-01 21:05:05               NaN
1           Deneb 2024-09-28 1900-01-01 22:00:01               NaN
2            Sadr 2024-09-28 1900-01-01 22:00:03               NaN
3   Epsilon Cygni 2024-09-28 1900-01-01 22:00:06               NaN
4          Altair 2024-09-28 1900-01-01 22:00:07                 W
5          Saturn 2024-09-28 1900-01-01 22:00:09                SE
6            Enif 2024-09-28 1900-01-01 22:01:05                SE
7         Schedar 2024-09-28 1900-01-01 22:02:03                NE
8       Fomalhaut 2024-09-28 1900-01-01 22:05:05                SE
9       Alpheratz 2024-09-29 1900-01-01 22:02:02                SE
10         Mirach 2024-09-29 1900-01-01 22:03:05                SE
11         Mirfak 2024-09-29 1900-01-01 22:02:06                NE
12        Polaris 2024-09-29 1900-01-01 22:03:00                 N
13         Kochab 2024-09-29 1900-01-01 22:03:03                NW
14        Tarazed 2024-09-29 1900-01-01 22:04:00                SW

In [ ]:
date = '2026-10-02'
constellations = pd.DataFrame({
    'Constellation': ['Canis Major', 'Taurus', 'Orion', 'Perseus', 'Auriga', 'Canis Minor', 'Cancer'],
    'Time': [620, 624, 632, 634, 641, 643, 644],
    'Date': [date] * 7,
    'Direction': ['SE', 'NaN', 'SE', 'W', 'W', 'NE', 'SE']
})

In [146]:
constellations['Date/Time'] = pd.to_datetime(constellations['Date'] + ' ' + constellations['Time'].astype(str), format='%Y-%m-%d %H%M', errors='coerce')
constellations.drop(columns=['Date', 'Time'], inplace=True)

In [148]:
constellations.to_latex(index=False, escape=False)

'\\begin{tabular}{lll}\n\\toprule\nConstellation & Direction & Date/Time \\\\\n\\midrule\nCanis Major & SE & 2026-10-02 06:20:00 \\\\\nTaurus & NaN & 2026-10-02 06:24:00 \\\\\nOrion & SE & 2026-10-02 06:32:00 \\\\\nPerseus & W & 2026-10-02 06:34:00 \\\\\nAuriga & W & 2026-10-02 06:41:00 \\\\\nCanis Minor & NE & 2026-10-02 06:43:00 \\\\\nCancer & SE & 2026-10-02 06:44:00 \\\\\n\\bottomrule\n\\end{tabular}\n'